In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
#Now to avoid the hectic situation we merge the two datsets like as below
movies = movies.merge(credits,on='title')

In [6]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [7]:
#We dont need all these columns so we just take the required columns like
# genres
# id
# keywords
# title
# cast
# crew
# overview

In [8]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]
movies

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [9]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace=True)

In [11]:
movies.duplicated().sum()

0

In [12]:
#IN the dataset genre column keywords,cast and crew column is in a weird format we need to convert it into a suitable format

In [13]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [14]:
# '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# here we need to convert this into [Action,Adventure,Fantasy,Science-Fiction]
# to do that we will create a function as below

In [15]:
import ast
#This library import ast which have function called literal_eval which will help to convert string into list
# ex: '[1,2,3]' this is string list with the help of literal_eval we can convert it into [1,2,3]
def converter(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [16]:
converter('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [17]:
movies['genres'] = movies['genres'].apply(converter)

In [18]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
movies['keywords'][0]
#Here keyword is also same like the genres so we need only the names so we can use the same function for keyword column also

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [20]:
movies['keywords'] = movies['keywords'].apply(converter)

In [21]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [22]:
#Next the cast column ,in cast column there is name of all actors who have acted ,we can take all the names so
#We prefer taking the first 3 names ,the function is similar to the function we have used for genre and keyword but
# A slight difference we does not need to iterate through all the names we need only first 3 names so we can create function as follow
def convert_3(obj):
    L=[]
    counter = 0 #This is use to know whether we have reached the 3 names,if counter=3 we need to break from the loop
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter = counter+1
        else:
            break
    return L

In [23]:
movies['cast'] = movies['cast'].apply(convert_3)

In [24]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [26]:
#Next a bit challenging is Crew column, we need to fetch only director name we can ignore the rest
#The function is similar to the one that we have used before but only difference is we have to fetch only the director name
#so the function is as follow
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [27]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [28]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [29]:
#Now we need to convert the overview into a list for convenience
movies['overview'] = movies['overview'].apply(lambda x:x.split())
#This will convert the overview into a list
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [30]:
#Now an important thing to do is, there is many name in the dataset like Sam worthington,Sam mendes etc
#Sam worthington is name of one person and Sam mendes is name of other person
#if the model return Sam ,Then it will confused whether it is Sam Mendes or Sam Worthington so to avoid this 
#We can remove the space between the names so to do that we do the following
movies['genres'] = movies['genres'].apply(lambda x :[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x :[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x :[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x :[i.replace(" ","") for i in x])

In [31]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [32]:
#Now overview,genres,keywords,cast and crew is in list we can concatenate all these into one column named tag
# And assign it to a new variable
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew'] 
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [33]:
# Now we can create a new dataframe which contain only movie_id,title and tags
new_df = movies[['movie_id','title','tags']]
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [34]:
#Now we can convert the tags list into string with a simple function as follows
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\user\AppData\Local\Temp\ipykernel_18288\165723490.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [35]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [36]:
#Now for convenience we can convert all the tags to lowercase
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\user\AppData\Local\Temp\ipykernel_18288\1622835029.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [37]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [40]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [43]:
def lemma(text):
    y=[]
    for i in text.split():
        y.append(lemmatizer.lemmatize(i))
   
    return " ".join(y)

In [44]:
new_df['tags'] = new_df['tags'].apply(lemma)
#We have used stemming to avoid repetiton of the words

C:\Users\user\AppData\Local\Temp\ipykernel_18288\3695307295.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lemma)

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(max_features = 5000,stop_words='english')
#We are using countvectorizer to convert the string 'tags' into vectors for similarity check
# we cannot check for similarity between movies with the help of the strings so we are using vectors to check the similarity
# Thats why we have used countvectorizer

In [46]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [47]:
vectors[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [48]:
# Now our main goal is movie recommendation so we have to check similarity between the movies
# we need to compare each movie with the rest of the movie to check the similarity
# we have already converted the tags of the movies to vector for similarity checking convenince
# For similarity check we will use cosine similarity function instead of eucledian distance
# Because in higher dimension eucledian distance is not realiable
# as distance increase similarity decrase 
# In cosine similarity each movie is checked with rest of the 5000 movies for similarity and it will result an array
# I will show the working in below

In [49]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [50]:
similarity.shape
#It gives 4806,4806 because we need to check each movie with the rest of the movie
#That is 1st movie with 4086 movies second movie with 4086 movies and so on therefore there will be total 4086x4086 checking

(4806, 4806)

In [51]:
#Now we need to define a function named recommed to for recommending movies based on similarity
#That is,when we give a movie the function should return top 5 similar movies corresponding to the given movie
#For example if we give avatar as the movie then the function should return the top 5 movies similar to avatar 
#for that we need movie index,then give the index of the movie to cosine similarity to check with the rest of the movies
#Then the step will be explained after creating the function

In [52]:
new_df[new_df['title']=='Avatar']

   movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a paraplegic marine is di...

In [53]:
new_df[new_df['title']=='Avatar'].index[0]

0

In [54]:
list(enumerate(similarity[0]))
#Here index and the similarity value can be seen with the help of the enumerate

[(0, 1.0000000000000002),
 (1, 0.022192536696569252),
 (2, 0.030258053075110584),
 (3, 0.02108328646387948),
 (4, 0.10461751379808998),
 (5, 0.05001620897253309),
 (6, 0.003173865582454401),
 (7, 0.08007280471688616),
 (8, 0.01889841779421964),
 (9, 0.024649371932694),
 (10, 0.032414118002385944),
 (11, 0.033856617780935086),
 (12, 0.025361132583537976),
 (13, 0.009603136261305436),
 (14, 0.03189457561639296),
 (15, 0.016870630122445166),
 (16, 0.01966175595523477),
 (17, 0.07028895787170561),
 (18, 0.06206443648323371),
 (19, 0.028022472889937467),
 (20, 0.014927950835743841),
 (21, 0.04183695330574722),
 (22, 0.01895365091584362),
 (23, 0.024673985523404877),
 (24, 0.01095616194227214),
 (25, 0.04586408326976951),
 (26, 0.0856710635775564),
 (27, 0.10067666658194777),
 (28, 0.04547512532528072),
 (29, 0.030674707444329034),
 (30, 0.017718459478522297),
 (31, 0.08093885021722244),
 (32, 0.03575068296254942),
 (33, 0.02337979205437067),
 (34, 0.0),
 (35, 0.024494159732975973),
 (36, 0.1019955146283699),
 (37, 0.034432703754659844),
 (38, 0.016608911409994077),
 (39, 0.0213643800500518),
 (40, 0.014722461702328412),
 (41, 0.08429598217487291),
 (42, 0.0),
 (43, 0.04146264959594287),
 (44, 0.007114512423734936),
 (45, 0.0581914523142678),
 (46, 0.07241393583427864),
 (47, 0.16602506167580477),
 (48, 0.027735917298831562),
 (49, 0.030633059509169985),
 (50, 0.03383619677550238),
 (51, 0.029586641511957182),
 (52, 0.0715594744773751),
 (53, 0.009429251970207756),
 (54, 0.008837773644611708),
 (55, 0.028105299795767626),
 (56, 0.05829972550119299),
 (57, 0.024673859496305246),
 (58, 0.008536544728673871),
 (59, 0.04268240797253934),
 (60, 0.018846242199189085),
 (61, 0.10051143046020422),
 (62, 0.016858834854458066),
 (63, 0.034729752053543325),
 (64, 0.009569500334757819),
 (65, 0.003326029014426451),
 (66, 0.006528440428062037),
 (67, 0.08509278899929702),
 (68, 0.05873210110913283),
 (69, 0.020280460163676153),
 (70, 0.01890331734100869),
 (71, 0.019767728901023837),
 (72, 0.052482921068873326),
 (73, 0.012505160691118246),
 (74, 0.1357936553140784),
 (75, 0.050353555296920795),
 (76, 0.01913569617836332),
 (77, 0.009843658229317626),
 (78, 0.014032213063757489),
 (79, 0.017677122070772235),
 (80, 0.020827290427623338),
 (81, 0.044913106020652814),
 (82, 0.03313866925343204),
 (83, 0.13561143326791517),
 (84, 0.05994230270361515),
 (85, 0.0534448284923988),
 (86, 0.03151913167911716),
 (87, 0.05614403754726529),
 (88, 0.037928152989701806),
 (89, 0.031885520735858604),
 (90, 0.01969778057344134),
 (91, 0.06703140368162935),
 (92, 0.025709843903946164),
 (93, 0.011584181316668683),
 (94, 0.10711535967309421),
 (95, 0.08996770297182959),
 (96, 0.020466365756714268),
 (97, 0.01810448957682726),
 (98, 0.018630352458133628),
 (99, 0.005217272208696985),
 (100, 0.02156935071791719),
 (101, 0.02126301701314582),
 (102, 0.04248936303138472),
 (103, 0.029959846572409264),
 (104, 0.011600451653160981),
 (105, 0.04910042123506407),
 (106, 0.01258865922090463),
 (107, 0.05382880809072387),
 (108, 0.08948792694560935),
 (109, 0.02177083509616287),
 (110, 0.005071061700499092),
 (111, 0.06064504796820132),
 (112, 0.01863490341279532),
 (113, 0.015353552571702376),
 (114, 0.01463636362141248),
 (115, 0.014206928536392117),
 (116, 0.014502104509843928),
 (117, 0.017501859005030016),
 (118, 0.005927138931007289),
 (119, 0.02590273586781404),
 (120, 0.0),
 (121, 0.02210706519529699),
 (122, 0.024481343631875797),
 (123, 0.04646043635449579),
 (124, 0.03191632864515379),
 (125, 0.029164299594222426),
 (126, 0.061455800258427645),
 (127, 0.07354994231347306),
 (128, 0.0),
 (129, 0.04051315700961526),
 (130, 0.00841142139003726),
 (131, 0.04304379285661437),
 (132, 0.0214933596873553),
 (133, 0.010871699122028901),
 (134, 0.05582990285603244),
 (135, 0.0),
 (136, 0.005762648430125948),
 (137, 0.031290971709360016),
 (138, 0.029183168707577922),
 (139, 0.03994918267932959),
 (140, 0.04358272323013995),
 (141, 0.050977162348986256),
 (142, 0.044700693946152496),
 (143, 0.019873214568975152),
 (144, 0.011804123083488865),
 (145, 0.0047086818594851716),
 (146, 0.0133688105570825),
 (147, 0.011549196730502245),
 (148, 0.05017384021175955),
 (149, 0.1041684086972508),
 (150, 0.11154752885328724),
 (151, 0.0849250230434265),
 (152, 0.021448956432598382),
 (153, 0.034788896887597585),
 (154, 0.012976642082991489),
 (155, 0.013276633355037728),
 (156, 0.035325270197833394),
 (157, 0.036828074297738565),
 (158, 0.07212543129756899),
 (159, 0.01641126809252746),
 (160, 0.04365736521873659),
 (161, 0.011509752504462994),
 (162, 0.00623970356670592),
 (163, 0.01228088354087693),
 (164, 0.017364968088609378),
 (165, 0.011047063297849118),
 (166, 0.0622842265531133),
 (167, 0.013386059455937876),
 (168, 0.07070805026723301),
 (169, 0.05586039636839052),
 (170, 0.03761353682320844),
 (171, 0.0065925876731883154),
 (172, 0.0715713192878722),
 (173, 0.017204395442760142),
 (174, 0.06343633835489011),
 (175, 0.014286850473380009),
 (176, 0.0072690355948328185),
 (177, 0.0),
 (178, 0.006560862646906758),
 (179, 0.040748909463406396),
 (180, 0.003989560646274269),
 (181, 0.004892015398895175),
 (182, 0.04145792963634621),
 (183, 0.025051757228551158),
 (184, 0.1110800400643744),
 (185, 0.01590848650902177),
 (186, 0.00737663075631251),
 (187, 0.039457127630945533),
 (188, 0.0038624530003889437),
 (189, 0.03907906349006186),
 (190, 0.030127402953458778),
 (191, 0.015551859750302746),
 (192, 0.014825883624524867),
 (193, 0.035103588532633304),
 (194, 0.0),
 (195, 0.020124175992646563),
 (196, 0.014048800687422657),
 (197, 0.013642985789204306),
 (198, 0.01650595450344843),
 (199, 0.046997724451744716),
 (200, 0.02084144032817883),
 (201, 0.0),
 (202, 0.00793287795279094),
 (203, 0.020353240031535783),
 (204, 0.020132718209937003),
 (205, 0.015412688783924246),
 (206, 0.046318120757750374),
 (207, 0.018409632019515596),
 (208, 0.03996151514002006),
 (209, 0.01265620940414564),
 (210, 0.027775114996386855),
 (211, 0.009598561026526356),
 (212, 0.01912626531291286),
 (213, 0.021702207128158943),
 (214, 0.006488198995553217),
 (215, 0.0178892801163038),
 (216, 0.013224577151255733),
 (217, 0.024404331322133814),
 (218, 0.007275834983549663),
 (219, 0.012664617798461534),
 (220, 0.10183069195501751),
 (221, 0.01185113291654286),
 (222, 0.04733020170632642),
 (223, 0.047711954211516736),
 (224, 0.025573823880801993),
 (225, 0.012732183928576453),
 (226, 0.006484454690529074),
 (227, 0.030039341469236376),
 (228, 0.05518388332476959),
 (229, 0.023063501706552407),
 (230, 0.027599281731540675),
 (231, 0.0),
 (232, 0.03091315537602469),
 (233, 0.025494767439377113),
 (234, 0.0206063302111451),
 (235, 0.037109644309072765),
 (236, 0.08286457480520977),
 (237, 0.013714996753524469),
 (238, 0.049473701033453214),
 (239, 0.07266272017581632),
 (240, 0.009497050649106433),
 (241, 0.02215311844379667),
 (242, 0.02330245421728981),
 (243, 0.03252069882660622),
 (244, 0.04949697655219083),
 (245, 0.02843497559138782),
 (246, 0.03214899395999582),
 (247, 0.0),
 (248, 0.008403594518647115),
 (249, 0.08229892396362057),
 (250, 0.0),
 (251, 0.03130132876041061),
 (252, 0.004096333759382001),
 (253, 0.02346130061487585),
 (254, 0.049999009704972376),
 (255, 0.0),
 (256, 0.022042949694397844),
 (257, 0.032105987475328286),
 (258, 0.008945535057965666),
 (259, 0.013427238654388784),
 (260, 0.15196971268239143),
 (261, 0.004299811994437351),
 (262, 0.030428840171150204),
 (263, 0.022342162025107054),
 (264, 0.0),
 (265, 0.009849703893129726),
 (266, 0.0500342151194295),
 (267, 0.013620358342856576),
 (268, 0.017020246218662324),
 (269, 0.007338566731907449),
 (270, 0.05052707058899936),
 (271, 0.017689587705081774),
 (272, 0.006413876359987529),
 (273, 0.004152875761789),
 (274, 0.03352124651737845),
 (275, 0.06332127200648506),
 (276, 0.019092078698233685),
 (277, 0.020265302172347482),
 (278, 0.04636177436025569),
 (279, 0.08900611262165588),
 (280, 0.0),
 (281, 0.07479080088125854),
 (282, 0.057610320707841674),
 (283, 0.0),
 (284, 0.0042559411791993195),
 (285, 0.003812960739609635),
 (286, 0.003984233931380858),
 (287, 0.025172848045284305),
 (288, 0.0),
 (289, 0.01554772492122551),
 (290, 0.013552557163297407),
 (291, 0.010553903521921692),
 (292, 0.026808692703592922),
 (293, 0.010479703407922073),
 (294, 0.07250161996648533),
 (295, 0.02500082755327037),
 (296, 0.011565989664985097),
 (297, 0.020715678925070133),
 (298, 0.0),
 (299, 0.010407056158963179),
 (300, 0.12055335274182045),
 (301, 0.12200583563829684),
 (302, 0.013073559984491646),
 (303, 0.004683158985121471),
 (304, 0.0287109632118052),
 (305, 0.11127185076205577),
 (306, 0.040722595491184004),
 (307, 0.04677026683893473),
 (308, 0.03619648732234334),
 (309, 0.019217270330470562),
 (310, 0.0069715138668101076),
 (311, 0.12729047486063275),
 (312, 0.06968609376960429),
 (313, 0.05460971334205038),
 (314, 0.0),
 (315, 0.022905335420734203),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.01737617458629475),
 (320, 0.00600084061588651),
 (321, 0.0),
 (322, 0.12030584765225089),
 (323, 0.006774531234718807),
 (324, 0.005975947901413834),
 (325, 0.04397783007292159),
 (326, 0.015767456195826146),
 (327, 0.010259222231060188),
 (328, 0.0),
 (329, 0.020211233017258634),
 (330, 0.034866573451023744),
 (331, 0.015812896993709337),
 (332, 0.06432950137499452),
 (333, 0.008663628864436402),
 (334, 0.033717878774512655),
 (335, 0.012512338719897),
 (336, 0.020913412819424777),
 (337, 0.0042431705892499675),
 (338, 0.0),
 (339, 0.012186983566488847),
 (340, 0.009847337400825095),
 (341, 0.036428308950084615),
 (342, 0.08255813190945224),
 (343, 0.011432736658950116),
 (344, 0.005444123912458066),
 (345, 0.004330272382618672),
 (346, 0.0),
 (347, 0.0),
 (348, 0.034610362529012714),
 (349, 0.02678684599152193),
 (350, 0.010513124218640223),
 (351, 0.0),
 (352, 0.006880514767311556),
 (353, 0.0038604587913201346),
 (354, 0.0),
 (355, 0.0067635675780720874),
 (356, 0.030461711587936882),
 (357, 0.0),
 (358, 0.018235052628989962),
 (359, 0.008643135349162431),
 (360, 0.0),
 (361, 0.026323905846443372),
 (362, 0.03987538358027672),
 (363, 0.04389754345719731),
 (364, 0.010154935754559767),
 (365, 0.047287244653160865),
 (366, 0.014275467383991106),
 (367, 0.0),
 (368, 0.0652753050651429),
 (369, 0.1081719737715383),
 (370, 0.012329848935421401),
 (371, 0.023015862242084295),
 (372, 0.02105348889116613),
 (373, 0.1181816032155919),
 (374, 0.009541767168192791),
 (375, 0.03294883539085306),
 (376, 0.011761304438563705),
 (377, 0.0),
 (378, 0.0),
 (379, 0.011771930439190257),
 (380, 0.0233103866558958),
 (381, 0.026648180367049665),
 (382, 0.0),
 (383, 0.009410016834920019),
 (384, 0.006664742917877344),
 (385, 0.0),
 (386, 0.003958553999005703),
 (387, 0.00467498966913303),
 (388, 0.0),
 (389, 0.03634918991686042),
 (390, 0.009887468365604857),
 (391, 0.01711265986784359),
 (392, 0.005770508133472921),
 (393, 0.0),
 (394, 0.004376400314584949),
 (395, 0.013652990575782347),
 (396, 0.004016449261839762),
 (397, 0.012002675819962044),
 (398, 0.0),
 (399, 0.005671157895419295),
 (400, 0.02661738973049308),
 (401, 0.021416367525751275),
 (402, 0.013165290356199915),
 (403, 0.028438617655471416),
 (404, 0.05199174689449616),
 (405, 0.025912593352445362),
 (406, 0.01257350546791199),
 (407, 0.006873705443534615),
 (408, 0.006441638606933864),
 (409, 0.0),
 (410, 0.04056448365920225),
 (411, 0.011514299173172707),
 (412, 0.03380628200239672),
 (413, 0.040175090732829856),
 (414, 0.007232478145812518),
 (415, 0.038500137589714364),
 (416, 0.015457402393018719),
 (417, 0.011414632762838472),
 (418, 0.02866428602808962),
 (419, 0.022972862146885938),
 (420, 0.04666800848722204),
 (421, 0.0),
 (422, 0.07634071225973901),
 (423, 0.03900110370976455),
 (424, 0.007686777618914602),
 (425, 0.02355008682519092),
 (426, 0.01728358687199215),
 (427, 0.006300131883691912),
 (428, 0.02569567445668395),
 (429, 0.0),
 (430, 0.038304371574448375),
 (431, 0.008860870911354601),
 (432, 0.0675074187343159),
 (433, 0.005827607253282108),
 (434, 0.0),
 (435, 0.01205683107765947),
 (436, 0.0),
 (437, 0.0049927938543836686),
 (438, 0.006459273105825509),
 (439, 0.023152972577671432),
 (440, 0.006228310137609631),
 (441, 0.010459510337241006),
 (442, 0.012472637694670989),
 (443, 0.028162173804131777),
 (444, 0.0),
 (445, 0.023352748504003644),
 (446, 0.004198298516813372),
 (447, 0.008040261770488905),
 (448, 0.020778201501621418),
 (449, 0.0338384916846),
 (450, 0.008331155949164663),
 (451, 0.00881748022425398),
 (452, 0.011574449983715351),
 (453, 0.004323674407502607),
 (454, 0.07497956740541949),
 (455, 0.0167522018194263),
 (456, 0.03232420287787231),
 (457, 0.018936776582624146),
 (458, 0.022655620748730433),
 (459, 0.009608262523145773),
 (460, 0.0066600467516658105),
 (461, 0.08566107963814451),
 (462, 0.01377809606507065),
 (463, 0.008239314446997756),
 (464, 0.0),
 (465, 0.0),
 (466, 0.11065587102995192),
 (467, 0.04255275702105564),
 (468, 0.005146914204120384),
 (469, 0.02337414289619941),
 (470, 0.013760699161617632),
 (471, 0.020910208710206234),
 (472, 0.022305682896703684),
 (473, 0.0495450923150172),
 (474, 0.0),
 (475, 0.041598492095663006),
 (476, 0.10034990094445533),
 (477, 0.0),
 (478, 0.0073453026196147785),
 (479, 0.05554328544441315),
 (480, 0.05037837052644175),
 (481, 0.0),
 (482, 0.006562432555354948),
 (483, 0.0527933314163245),
 (484, 0.007383553072432883),
 (485, 0.016102357446964966),
 (486, 0.014766139996300852),
 (487, 0.061987578234955196),
 (488, 0.03631565093940024),
 (489, 0.0),
 (490, 0.03627255044342566),
 (491, 0.044698146369968196),
 (492, 0.03198766407379117),
 (493, 0.00412228463911736),
 (494, 0.0),
 (495, 0.10080488894021847),
 (496, 0.0),
 (497, 0.0),
 (498, 0.016610632990922965),
 (499, 0.0),
 (500, 0.004752473638177578),
 (501, 0.03890668232216443),
 (502, 0.09618935968206438),
 (503, 0.01820817815667502),
 (504, 0.0),
 (505, 0.05363860275177794),
 (506, 0.0269198641970894),
 (507, 0.14762272285515823),
 (508, 0.023030068977441906),
 (509, 0.005652350798164714),
 (510, 0.04877031129135134),
 (511, 0.023243554867606955),
 (512, 0.031619184580591),
 (513, 0.12157941166424611),
 (514, 0.014249437631851844),
 (515, 0.00586834676688193),
 (516, 0.005375768822592909),
 (517, 0.0),
 (518, 0.009533211921455372),
 (519, 0.0),
 (520, 0.0),
 (521, 0.005993469261735907),
 (522, 0.0),
 (523, 0.010166123999293241),
 (524, 0.0),
 (525, 0.004507785224121781),
 (526, 0.0),
 (527, 0.0),
 (528, 0.0041328473402298515),
 (529, 0.09921823407637077),
 (530, 0.023364646920528732),
 (531, 0.009995713967389597),
 (532, 0.019758587965533498),
 (533, 0.03248626306891606),
 (534, 0.018527279793636088),
 (535, 0.049539334261365725),
 (536, 0.02661736338300113),
 (537, 0.01783996459493753),
 (538, 0.0),
 (539, 0.16952860278378304),
 (540, 0.011302849742825033),
 (541, 0.04607721777839657),
 (542, 0.009314210099588896),
 (543, 0.023665148561514547),
 (544, 0.012262890002039123),
 (545, 0.009181354851727726),
 (546, 0.03063830983033063),
 (547, 0.02584557788209882),
 (548, 0.0),
 (549, 0.0830386334248107),
 (550, 0.017005872860318537),
 (551, 0.008884602586178507),
 (552, 0.0),
 (553, 0.0058484833245731685),
 (554, 0.0),
 (555, 0.014156124338419635),
 (556, 0.005132080609167013),
 (557, 0.14995743928128802),
 (558, 0.0),
 (559, 0.0074719960132114596),
 (560, 0.008756376384538333),
 (561, 0.007593180437269241),
 (562, 0.00638506905197885),
 (563, 0.0106104068188963),
 (564, 0.059281481862782454),
 (565, 0.012849983238568445),
 (566, 0.005794489736108804),
 (567, 0.006253995271901936),
 (568, 0.06809563493634001),
 (569, 0.022431884371228186),
 (570, 0.05300387839979785),
 (571, 0.021070251144122337),
 (572, 0.028945908982923547),
 (573, 0.0036727031946828786),
 (574, 0.004375052607161085),
 (575, 0.015433598980413035),
 (576, 0.011334855867477697),
 (577, 0.10321971370479359),
 (578, 0.018181937240180544),
 (579, 0.09578654707751891),
 (580, 0.0043654251157869296),
 (581, 0.06562821832897678),
 (582, 0.18890026598187762),
 (583, 0.015488308141020816),
 (584, 0.015853507893893847),
 (585, 0.0),
 (586, 0.008803098438510168),
 (587, 0.06032285292433478),
 (588, 0.016287986898076205),
 (589, 0.046679693913743096),
 (590, 0.006304253750157602),
 (591, 0.021836430705122468),
 (592, 0.0057051693144088925),
 (593, 0.0),
 (594, 0.011085629554593388),
 (595, 0.12570053052842914),
 (596, 0.029852492549486534),
 (597, 0.016579345228861796),
 (598, 0.009891636754510385),
 (599, 0.02285590892066773),
 (600, 0.0324251355621588),
 (601, 0.009576585530939569),
 (602, 0.04006853879982298),
 (603, 0.009568337106452418),
 (604, 0.014427121570850392),
 (605, 0.015875730059278188),
 (606, 0.0),
 (607, 0.01442465227129476),
 (608, 0.0),
 (609, 0.01229847530216455),
 (610, 0.011894958350198903),
 (611, 0.00434889302479553),
 (612, 0.017946814291472227),
 (613, 0.006835882964451764),
 (614, 0.05385530905642574),
 (615, 0.006134825418459197),
 (616, 0.021679566988350343),
 (617, 0.037663400039712316),
 (618, 0.025925575552182372),
 (619, 0.0),
 (620, 0.0),
 (621, 0.030648223980033334),
 (622, 0.003799925720577539),
 (623, 0.0),
 (624, 0.051403224143506274),
 (625, 0.006956497796268835),
 (626, 0.052378818750223474),
 (627, 0.027448396981114676),
 (628, 0.0),
 (629, 0.02125965245178566),
 (630, 0.005563843366059361),
 (631, 0.006156118356970827),
 (632, 0.044362389588022556),
 (633, 0.004040673105208436),
 (634, 0.035011351695164145),
 (635, 0.06237510638600201),
 (636, 0.010320608232815734),
 (637, 0.026863799705331683),
 (638, 0.007544960245174063),
 (639, 0.0),
 (640, 0.025070474613669437),
 (641, 0.0),
 (642, 0.0),
 (643, 0.06373955435102026),
 (644, 0.0119649706286501),
 (645, 0.009270113386484197),
 (646, 0.04690218147383098),
 (647, 0.06397915466160259),
 (648, 0.007475422577230379),
 (649, 0.0),
 (650, 0.00940117918669224),
 (651, 0.0),
 (652, 0.0046583691897730106),
 (653, 0.03884396401261922),
 (654, 0.02184915068145331),
 (655, 0.004194201200412559),
 (656, 0.0),
 (657, 0.008606783312982634),
 (658, 0.013155840466145766),
 (659, 0.005112871095713761),
 (660, 0.021461733352311312),
 (661, 0.09469042971203265),
 (662, 0.0),
 (663, 0.0),
 (664, 0.01406588016585721),
 (665, 0.016405301076891705),
 (666, 0.027618207898360028),
 (667, 0.0),
 (668, 0.021544420188539443),
 (669, 0.026980972825510006),
 (670, 0.003890558902676),
 (671, 0.022320267919550295),
 (672, 0.03592173596861981),
 (673, 0.007168858403133271),
 (674, 0.04383816124945199),
 (675, 0.012154335362778395),
 (676, 0.0060522026935803195),
 (677, 0.004846603418765561),
 (678, 0.012402002513003845),
 (679, 0.0),
 (680, 0.03905633741803734),
 (681, 0.0070626032094734175),
 (682, 0.005584113730621172),
 (683, 0.009587968798780986),
 (684, 0.0),
 (685, 0.006389948071912693),
 (686, 0.0),
 (687, 0.04610474192943785),
 (688, 0.021438548992827794),
 (689, 0.0),
 (690, 0.010380565427029004),
 (691, 0.023140334670607124),
 (692, 0.08314809997289481),
 (693, 0.0),
 (694, 0.003838000956910728),
 (695, 0.013213445826198569),
 (696, 0.0),
 (697, 0.0),
 (698, 0.005545993696627847),
 (699, 0.0),
 (700, 0.00552707002280628),
 (701, 0.037455669446407915),
 (702, 0.004272569567699799),
 (703, 0.004169794046092698),
 (704, 0.04354777958748754),
 (705, 0.005489081755860875),
 (706, 0.005737614731708047),
 (707, 0.0),
 (708, 0.004379723695359691),
 (709, 0.0),
 (710, 0.02643846458329284),
 (711, 0.014023476546110752),
 (712, 0.0),
 (713, 0.005603266402917199),
 (714, 0.0),
 (715, 0.026988053733747706),
 (716, 0.0062103023975412),
 (717, 0.0),
 (718, 0.010143520055620442),
 (719, 0.0),
 (720, 0.007720270079666951),
 (721, 0.007696368724515108),
 (722, 0.0),
 (723, 0.008111228126287198),
 (724, 0.004604238337498774),
 (725, 0.0),
 (726, 0.0),
 (727, 0.006412815833087718),
 (728, 0.021031814827715215),
 (729, 0.019403598536686398),
 (730, 0.015785357884654967),
 (731, 0.011486600555919046),
 (732, 0.01778708872695941),
 (733, 0.00971703360724915),
 (734, 0.011476224306215147),
 (735, 0.01147751705706422),

In [55]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]
#Here key=lambda x:x[1] is a function which tells the sorted function to sort the values based on the similarity value not index
#That is we can see first value represent the index and second value represent the similarity value
#ex: (0,1.00)
    #(1,0.083) etc
# here 0 and 1 represent the index value and 1.00 and 0.083 represent the similarity value
# by default sorted function sort based on the index value but when we use to lambda function
# lambda x:x[1] we tell the sorted function to sort base on the similarity value
# x:x[1] tell to sort by similarity value x:x[0] will tell to sort by index value
# [1:6] represent we want first 5 movie values not all

[(2405, 0.26811042301060134),
 (3728, 0.19390116484537673),
 (582, 0.18890026598187762),
 (942, 0.1775623733757422),
 (3606, 0.17735967809203207)]

In [56]:
def recommend(movie):
    movie_index = new_df[new_df['title']== movie].index[0] #This will return the index of any movie given
    distances = similarity[movie_index] #This will do the cosine similarity so that distance between movie can be get
    movie_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6] #first 5 movies will be returned
    for i in movie_list:
        print(new_df.iloc[i[0]].title) #This will print the name of the movie that is similar to the given movie
        print(i[1])
        print(i[0])

In [65]:
recommend('Pirates of the Caribbean: The Curse of the Black Pearl')

The Pirate
0.33807310369134635
3824
VeggieTales: The Pirates Who Don't Do Anything
0.29630272440243527
2592
Pirates of the Caribbean: Dead Man's Chest
0.2892076009775336
12
The Pirates! In an Adventure with Scientists!
0.2671638151743424
848
Pirates of the Caribbean: On Stranger Tides
0.26399068500104994
17

In [134]:
recommend('Batman Begins')

The Dark Knight
0.40218090755486674
65
Batman
0.35434169344615046
1361
Batman
0.3340765523905305
1360
The Dark Knight Rises
0.3177444546511212
3
10th & Wolf
0.3120099844792576
3295

In [69]:
new_df.iloc[12].title

"Pirates of the Caribbean: Dead Man's Chest"

In [68]:
new_df[new_df['title'] == "Pirates of the Caribbean: Dead Man's Chest"].index[0]

12

In [63]:
import pickle
pickle.dump(new_df,open('movies1.pkl','wb'))

In [64]:
pickle.dump(similarity,open('similarity1.pkl','wb'))